spring:
    config:
        import: optional:file:.env[.properties]
    mongodb:
        uri: ${MONGODB_URI}
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 8082

eureka:
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

rabbitmq:
    exchange:
        name: fitness.exchange
    queue: 
        name: activity.queue
    routing : 
        key: activity.tracking