server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/fitness_user_db
        username: postgres
        password: shiro123
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

